---
title: "Prelim report"
author: "Junker"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
      keep_md: true
      toc: true
      toc_float: true
      toc_depth: 3
      numbered_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

source("./packages.R")
stream_order = factor(c("hver", "st6","st9", "st7","oh2","st14"))#stream ordering
stream_temp_labels = c("27.2","17.6","11.2","5.8","5.5","5.0")#stream annual temperature labels
oce_temp_pos = c(256,212,168,124,80,1)#color positions in 'temperature' list of ocecolors

drake::loadd("spp_rankings")

```

## Analysis

Preliminary figures for exploring data analyses and figures.

### Histograms of PB, M, and Biomass among streams.

```{r pb historgram, echo = FALSE, warnings = FALSE}
pb_df = spp_rankings[['PB_spp_rank']] %>% bind_rows %>% dplyr::filter(pb_y_mean >0) %>% dplyr::mutate(site_id = factor(site_id, levels = rev(stream_order)))
bio_df = spp_rankings[['bio_spp_rank']] %>% bind_rows %>% dplyr::filter(bio_mg_m_mean >0 | is.na(bio_mg_m_mean)) %>% dplyr::mutate(site_id = factor(site_id, levels = rev(stream_order)))
M_df = spp_rankings[['M_spp_rank']] %>% bind_rows %>% dplyr::filter(M_mg_ind_mean >0 | is.na(M_mg_ind_mean)) %>% dplyr::mutate(site_id = factor(site_id, levels = rev(stream_order)))

pb_boxplot = ggplot(pb_df,aes(x = site_id, y = log10(pb_y_mean))) + geom_violin(aes(fill = site_id), alpha = 0.5) +
  geom_jitter(aes( fill = site_id),color = 'black', size = 2, shape = 21, alpha = 0.5) +
  scale_fill_manual(values = rev(ocecolors[['temperature']][oce_temp_pos]), labels = rev(stream_temp_labels)) +
  theme(axis.title.x = element_blank(), legend.title = element_blank(), legend.position = c(0,0), legend.justification = c(0,0),
        legend.background = element_rect(fill = 'transparent', colour = NA))
# pb_boxplot

M_boxplot = ggplot(M_df,aes(x = site_id, y = log10(M_mg_ind_mean))) + geom_violin(aes(fill = site_id), alpha = 0.5) +
  geom_jitter(aes( fill = site_id),color = 'black', size = 2, shape = 21, alpha = 0.5) +
  scale_fill_manual(values = rev(ocecolors[['temperature']][oce_temp_pos]), labels = rev(stream_temp_labels)) +
  theme(axis.title.x = element_blank(), legend.title = element_blank(), legend.position = "none")

bio_boxplot = ggplot(bio_df,aes(x = site_id, y = log10(bio_mg_m_mean))) + geom_violin(aes(fill = site_id), alpha = 0.5) +
  geom_jitter(aes( fill = site_id),color = 'black', size = 2, shape = 21, alpha = 0.5) +
  scale_fill_manual(values = rev(ocecolors[['temperature']][oce_temp_pos]), labels = rev(stream_temp_labels)) +
  theme(axis.title.x = element_blank(), legend.title = element_blank(),legend.position = "none")

grid.arrange(pb_boxplot, M_boxplot, bio_boxplot, ncol = 3)

```

### Rank plots 



## Reproducibility

<details><summary>Reproducibility receipt</summary>

```{r}
## datetime
Sys.time()

## repository
if(requireNamespace('git2r', quietly = TRUE)) {
  git2r::repository()
} else {
  c(
    system2("git", args = c("log", "--name-status", "-1"), stdout = TRUE),
    system2("git", args = c("remote", "-v"), stdout = TRUE)
  )
}

## session info
sessionInfo()
```

</details>
